@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMkBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwidmVyaWZ5Ijp0cnVlLCJpYXQiOjE2ODEzMTM0OTl9.mYT-62CP3VPCJ95H1eOZJwdNxmkpJlVcns19XDh_66g
### REGISTER
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "email": "examp2@email.com",
  "password": "nhewew83jdol$%&^./`"
}
###
### REGISTER DUPLICATE
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "email": "exampErr@email.com",
  "password": "nhewew83jdol$%&^./`"
}
###

### LOGIN
GET http://nodejs.yurgo.fun/api/users/login
Content-Type: application/json

{
  "email": "examp2@email.com",
  "password": "nhewew83jdol$%&^./`"
}
###
### CURRENT
GET  http://nodejs.yurgo.fun/api/users/current
Accept: application/json
Authorization: Bearer {{token}}
###
### LOGOUT
POST http://localhost:3000/api/users/logout
Content-Type: application/json
Authorization: Bearer {{token}}
###


PATCH http://nodejs.yurgo.fun/api/users/contacts/6408873f115c40d0247c37a6/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMkBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3ODM3MTIyfQ.PiybbW_Fw3HJ3KQaa7CQPKJCSvMYtKBdmx3RHZ0Ng_w

{
  "favorite": "true"
}
###
### NO USER
PATCH http://localhost:3000/api/contacts/6401c6c4d15d964a6208a1f2/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMkBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3ODM3MTIyfQ.PiybbW_Fw3HJ3KQaa7CQPKJCSvMYtKBdmx3RHZ0Ng_w

{
  "favorite": "false"
}
###

###
POST http://localhost:3000/api/contacts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMkBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3ODM3MTIyfQ.PiybbW_Fw3HJ3KQaa7CQPKJCSvMYtKBdmx3RHZ0Ng_w

{
  "name": "joe2222oooNOWWW08",
  "email": "examp@email.com",
  "phone": "+111111162222"
}
###

GET http://localhost:3000/api/contacts/64005ebe93f0975ba9b7bdd7
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMkBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3ODM3MTIyfQ.PiybbW_Fw3HJ3KQaa7CQPKJCSvMYtKBdmx3RHZ0Ng_w
###

### GET All auth PAGINATION
GET http://localhost:3000/api/contacts?page=1&limit=4
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMkBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3ODM3MTIyfQ.PiybbW_Fw3HJ3KQaa7CQPKJCSvMYtKBdmx3RHZ0Ng_w
###

### CYCLIC DEPLOY
https://outstanding-jade-prawn.cyclic.app/api/contacts?page=2&limit=4
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMkBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3ODM3MTIyfQ.PiybbW_Fw3HJ3KQaa7CQPKJCSvMYtKBdmx3RHZ0Ng_w


### GET All auth PAGINATION & FAVORITE
GET http://localhost:3000/api/contacts?page=1&limit=5&favorite=true
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMkBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3ODM3MTIyfQ.PiybbW_Fw3HJ3KQaa7CQPKJCSvMYtKBdmx3RHZ0Ng_w
###



#user2:






### GET simple
GET http://localhost:3000/api/contacts
Accept: application/json
###
GET http://localhost:3000/api/contacts/64005ebe93f0975ba9b7bdd7
Accept: application/json
###

### BY ID no owner
GET http://localhost:3000/api/contacts/63f1e79d4dc50cca4f43735b
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE
###
### BY ID with owner
GET http://localhost:3000/api/contacts/64005ebe93f0975ba9b7bdd7
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE
###

POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "name": "joeNOWWW",
  "email": "eeemmmaaaiiilll",
  "phone": "11111116"
}
###
POST http://localhost:3000/api/contacts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE

{
  "name": "joeNOWWW32",
  "email": "examp@email.com",
  "phone": "+111111162222"
}
###


DELETE http://localhost:3000/api/contacts/6408873f115c40d0247c37a6
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMkBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3ODM3MTIyfQ.PiybbW_Fw3HJ3KQaa7CQPKJCSvMYtKBdmx3RHZ0Ng_w

###
GET http://localhost:3000/api/contacts/6408873f115c40d0247c37a6
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE

###
// todo: get by wrong id????

###
PATCH http://localhost:3000/api/contacts/63f1e79d4dc50cca4f43735b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE

{
  "phone": "+380677490000"
}
###
GET http://localhost:3000/api/contacts/63f1e79d4dc50cca4f43735b
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE

###
PATCH http://localhost:3000/api/contacts/63f1e79d4dc50cca4f43735b/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE


{
  "favorite": "true"
}
###

GET http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "examp1@email.com",
  "password": "nhd783jdol"
}

###

### GET All auth
GET http://localhost:3000/api/contacts
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE
###

### GET All auth PAGINATION
GET http://localhost:3000/api/contacts?page=1&limit=5
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE
###

POST http://localhost:3000/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzA3MzM2fQ.t30w3P_9BJiGo4xMVFANZAuA2iFy6AvBvQIUEMIenDM
###

## current
GET  http://localhost:3000/api/users/current
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzQwMjE3fQ.L4gx-fCWlbw0g5Y9fhL9w1H92oyKJCzPA5ULBB-OhtE
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wMUBlbWFpbC5jb20iLCJzdWJzY3JpcHRpb24iOiJzdGFydGVyIiwiaWF0IjoxNjc3NzA3MzM2fQ.t30w3P_9BJiGo4xMVFANZAuA2iFy6AvBvQIUEMIenDM
###
