@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2JiM2ZjZDgxNWZhNzcyYjU2N2M0ZSIsImlhdCI6MTY4MTY1MTU3MCwiZXhwIjoxNjgxNjU4NzcwfQ.kZS53DGCWSQ_KvWkQep46PogDWLlsUeBZfJ3zPKitCI

### * LOGIN
POST http://localhost:3003/api/auth/login
Content-Type: application/json

{
    "email": "Jimmy2updated@email.com",
    "password": "1234567"
}

### * UPDATE
PUT http://localhost:3003/api/auth/643bb3fcd815fa772b567c4e
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "Jimmy2updated@email.com"
}

### * REGISTER
POST http://localhost:3003/api/auth/register
Content-Type: application/json

{
   "name": "JimmyTest2",
    "email": "Jimmy2@email.com",
    "password": "1234567"
}
### * SUBSCRIBE
POST http://localhost:3003/api/subscribe
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "emailToSubscribe": "yurgo@ptotonmail.com"
}

